# all relative paths are relative to your current working directory

DB:
  URL: sqlite+aiosqlite:///./data/uirpsoftball.db
UVICORN:
  host: 0.0.0.0
  port: 8080
  reload: true
OPENAPI_SCHEMA_PATH: ../openapi_schema.json
